### PR TITLE
Added youtu.be, removed www as it shouldnt be required

### PR DESCRIPTION
**Pull request by L0laapk3**

### CODE REVIEW

**Comment by tarehart** [comment]
Removing www looks troublesome to me:

```
PS C:\Users\tareh> py -3.7                                                                                              Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.parse import urlparse
>>> urlparse('https://www.youtube.com/watch?v=N9sIpnsnDd8')
ParseResult(scheme='https', netloc='www.youtube.com', path='/watch', params='', query='v=N9sIpnsnDd8', fragment='')
>>>      
```

**Comment by L0laapk3** [comment]
my bad. My intention was to also accept url's without `www.` such as:
https://youtube.com/watch?v=dQw4w9WgXcQ
since they are not required for any of the websites in that list.
How do you feel about doing some manual parsing logic after urlparse, such as: if the number of dots in netloc is 2, attempt to remove (or add) leading "www." if present?

**Comment by nathanielmoon** [comment]
Hi, I'm new to the community, but found this in the `github` channel on discord. It is not uncommon for links to contain an arbitrary number of dots, take `https://www.docs.google.com/` for example. 

Probably to best solution here is to 1). Switch the whitelist from being a `list` to being `set`, which will bring down the runtime complexity from O(n) to O(1) and 2). Implement a function called `check_whitelist` that looks up both www and non www variants.

**Comment by tarehart** [comment]
Welcome! That's a good suggestion, another option is to install the tldextract package. https://stackoverflow.com/questions/44021846/extract-domain-name-from-url-python

**Comment by nathanielmoon** [comment]
Thanks =) I'm a sucker for avoiding dependencies, but that package looks like it's exactly what's needed, though I would still convert the whitelist to a hashed data structure to speed things up

**Comment by L0laapk3** [comment]
I checked out what tldextract does, and for subdomain it does little more than '.'.split(url), pick off the front parts, join it back together. stripping www. from the beginning should do the trick.

**Pull request merged**
